# SPDX-FileCopyrightText: 2021-2024 City of Oulu
#
# SPDX-License-Identifier: LGPL-2.1-or-later

version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "Europe/Helsinki"
  - package-ecosystem: "npm"
    directory: "/e2e"
    schedule:
      interval: "daily"
      time: "06:30"
      timezone: "Europe/Helsinki"
    ignore:
      - dependency-name: "@playwright/test" # version must match with core
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-patch"]
    groups:
      jest:
        patterns:
          - "@types/jest"
          - "jest*"
          - "ts-jest"
        exclude-patterns:
          - "jest-junit"
      lodash:
        patterns:
          - "lodash"
          - "@types/lodash"
      react:
        patterns:
          - "react"
          - "react-dom"
      typescript:
        patterns:
          - "tslib"
          - "typescript"
  - package-ecosystem: "docker"
    directories:
      - "/scheduled-tasks/logs"
      - "/scheduled-tasks/certificate-check"
      - "/scheduled-tasks/reporting"
    schedule:
      interval: "daily"
      time: "06:30"
      timezone: "Europe/Helsinki"
  - package-ecosystem: "gradle"
    directory: "/service"
    schedule:
      interval: "daily"
      time: "06:30"
      timezone: "Europe/Helsinki"
    ignore:
      - dependency-name: "com.sun.xml.bind:jaxb-xjc"
      - dependency-name: "com.sun.xml.bind:jaxb-impl"
