# SPDX-FileCopyrightText: 2021 City of Oulu
#
# SPDX-License-Identifier: LGPL-2.1-or-later

spring:
  application:
    name: "evakaoulu-service"
#logging:
#  level:
#    root: TRACE
evaka:
  oph:
    organizer_oid: "1.2.246.562.10.80381044462"
    organizer_id: "90"
    municipality_code: "564"
  fee_decision:
    min_date: "2019-01-01"