# SPDX-FileCopyrightText: 2021 City of Oulu
#
# SPDX-License-Identifier: LGPL-2.1-or-later

# Docker compose for creating local dev databases
#
version: '3.5'

services:
  db:
    build:
      context: ../evaka/compose/db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: "pg_isready -U postgres"
      interval: 2s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: '[ "$$(redis-cli -h 127.0.0.1 ping)" == "PONG" ]'
      interval: 1s
      timeout: 5s
      retries: 5

  s3:
    image: adobe/s3mock:4.1.1
    ports:
      - "9191:9191"
      - "9876:9191" # for core tests
    volumes:
      - s3-data:/data
    environment:
      ROOT: /data
      initialBuckets: scheduled-task-reporting,static
      JAVA_TOOL_OPTIONS: "-XX:UseSVE=0 -XX:+IgnoreUnrecognizedVMOptions"
    healthcheck:
      test: [ "CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9090" ]
      interval: 1s
      timeout: 5s
      retries: 5

  sftp:
    image: atmoz/sftp:alpine
    ports:
      - "2222:22"
    volumes:
      - ../evaka/compose/sftp/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key
      - ../evaka/compose/sftp/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key
    command: foo:pass:::upload

  dummy-idp:
    build:
      context: ../evaka/dummy-idp
    init: true
    restart: on-failure
    ports:
      - "9090:9090"

volumes:
  db-data:
    driver: local
  s3-data:
    driver: local
