# SPDX-FileCopyrightText: 2021 City of Oulu
#
# SPDX-License-Identifier: LGPL-2.1-or-later

# Docker compose for trying out the evakaoulu/service docker image locally
# Scavenged from evaka integration testing and e2e compose files
#
version: '3.5'

services:
  db:
    build:
      context: ../evaka/compose/db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: "pg_isready -U postgres"
      interval: 2s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: '[ "$$(redis-cli -h 127.0.0.1 ping)" == "PONG" ]'
      interval: 1s
      timeout: 5s
      retries: 5

  s3:
    image: adobe/s3mock:4.1.1
    ports:
      - "9876:9191"
    volumes:
      - s3-data:/data
    environment:
      ROOT: /data
      initialBuckets: "static"
      JAVA_TOOL_OPTIONS: "-XX:UseSVE=0 -XX:+IgnoreUnrecognizedVMOptions"
    healthcheck:
      test: [ "CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9090" ]
      interval: 1s
      timeout: 5s
      retries: 5

  sftp:
    image: atmoz/sftp:alpine
    ports:
      - "2222:22"
    volumes:
      - ../evaka/compose/sftp/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key
      - ../evaka/compose/sftp/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key
    command: foo:pass:::upload

  dummy-idp:
    build:
      context: ../evaka/dummy-idp
    init: true
    restart: on-failure
    ports:
      - "9090:9090"

  evakaoulu-srv:
    image: ${EVAKA_SRV_IMAGE}
    ports:
      - "8888:8888"
    hostname: evakaoulu-srv
    depends_on:
      - db
    env_file:
      - .env
    environment:
      VOLTTI_ENV: local
      SPRING_PROFILES_ACTIVE: local,evakaoulu-local,evakaoulu
      SPRING_PROFILES_INCLUDE: enable_dev_api,enable_mock_integration_endpoint
      JAVA_OPTS: -server -Djava.security.egd=file:/dev/./urandom -Xms1024m -Xss512k -Xmx1024m -XX:TieredStopAtLevel=1
      EVAKA_DATABASE_FLYWAY_USERNAME: ${EVAKA_SERVICE_FLYWAY_USERNAME}
      EVAKA_DATABASE_FLYWAY_PASSWORD: ${EVAKA_SERVICE_FLYWAY_PASSWORD}
      EVAKA_DATABASE_URL: jdbc:postgresql://${EVAKA_DATABASE_HOST}:${EVAKA_DATABASE_PORT}/${EVAKA_SERVICE_DATABASE_NAME}
      EVAKA_DATABASE_USERNAME: ${EVAKA_SERVICE_APPLICATION_USERNAME}
      EVAKA_DATABASE_PASSWORD: ${EVAKA_SERVICE_APPLICATION_PASSWORD}
      SPRING_MAIN_BANNER_MODE: "off"
      # DEBUG: "true"
      # LOGGING_LEVEL_FI_ESPOO_EVAKA: DEBUG
      EVAKA_ASYNC_JOB_RUNNER_DISABLE_RUNNER: "true"
      EVAKA_BUCKET_DECISIONS: evaka-daycaredecisions-dev
      EVAKA_BUCKET_FEE_DECISIONS: evaka-paymentdecisions-dev
      EVAKA_LOCAL_S3_URL: https://s3:9191
      EVAKA_BUCKET_PROXY_THROUGH_NGINX: "true"
      EVAKA_PASSWORD_BLACKLIST_DIRECTORY: /opt/password-blacklists
      ESPOO_INTEGRATION_INVOICE_ENABLED: "false"
      EVAKA_INTEGRATION_KOSKI_ENABLED: "false"
      EVAKA_INTEGRATION_SFI_ENABLED: "false"
      EVAKA_INTEGRATION_VARDA_URL: "http://localhost:8888/mock-integration/varda/api"
      EVAKA_INTEGRATION_BASIC_AUTH: ""
    restart: unless-stopped


volumes:
  db-data:
    driver: local
  s3-data:
    driver: local
