name: 'Automerge dependabot submodule update PRs'
on:
  pull_request:

permissions:
  pull-requests: write
  contents: write

jobs:
  automerge:
    runs-on: ubuntu-latest

    if: ${{ github.actor == 'dependabot[bot]' && startsWith(github.head_ref, 'dependabot/submodules/') }}

    steps:
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
